function dy = three_layer_OR_circuit_design_ode(t,y) 
a=1;b=2;c=3;d=4;e=5;
f=6;g=7;h=8;o=9;ORgate_A_I__i=10;
ORgate_B_I__i=11;ORthd_I=12;i=13;ORgate_C_J__j=14;ORgate_D_J__j=15;
ORthd_J=16;j=17;ORgate_E_K__k=18;ORgate_F_K__k=19;ORthd_K=20;
k=21;ORgate_G_L__l=22;ORgate_H_L__l=23;ORthd_L=24;l=25;
ORgate_I_M__m=26;ORgate_J_M__m=27;ORthd_M=28;m=29;ORgate_K_N__n=30;
ORgate_L_N__n=31;ORthd_N=32;n=33;ORgate_M_O__o=34;ORgate_N_O__o=35;
ORthd_O=36;

k_app=10^6;
k_app_thd=10^7;
dy=zeros(36,1);

dy(a)=-k_app*y(a)*y(ORgate_A_I__i);
dy(b)=-k_app*y(b)*y(ORgate_B_I__i);
dy(c)=-k_app*y(c)*y(ORgate_C_J__j);
dy(d)=-k_app*y(d)*y(ORgate_D_J__j);
dy(e)=-k_app*y(e)*y(ORgate_E_K__k);
dy(f)=-k_app*y(f)*y(ORgate_F_K__k);
dy(g)=-k_app*y(g)*y(ORgate_G_L__l);
dy(h)=-k_app*y(h)*y(ORgate_H_L__l);
dy(o)=-k_app_thd*y(o)*y(ORthd_O)+k_app*y(m)*y(ORgate_M_O__o)+k_app*y(n)*y(ORgate_N_O__o);
dy(ORgate_A_I__i)=-k_app*y(a)*y(ORgate_A_I__i);
dy(ORgate_B_I__i)=-k_app*y(b)*y(ORgate_B_I__i);
dy(ORthd_I)=-k_app_thd*y(i)*y(ORthd_I);
dy(i)=-k_app_thd*y(i)*y(ORthd_I)-k_app*y(i)*y(ORgate_I_M__m)+k_app*y(a)*y(ORgate_A_I__i)+k_app*y(b)*y(ORgate_B_I__i);
dy(ORgate_C_J__j)=-k_app*y(c)*y(ORgate_C_J__j);
dy(ORgate_D_J__j)=-k_app*y(d)*y(ORgate_D_J__j);
dy(ORthd_J)=-k_app_thd*y(j)*y(ORthd_J);
dy(j)=-k_app_thd*y(j)*y(ORthd_J)-k_app*y(j)*y(ORgate_J_M__m)+k_app*y(c)*y(ORgate_C_J__j)+k_app*y(d)*y(ORgate_D_J__j);
dy(ORgate_E_K__k)=-k_app*y(e)*y(ORgate_E_K__k);
dy(ORgate_F_K__k)=-k_app*y(f)*y(ORgate_F_K__k);
dy(ORthd_K)=-k_app_thd*y(k)*y(ORthd_K);
dy(k)=-k_app_thd*y(k)*y(ORthd_K)-k_app*y(k)*y(ORgate_K_N__n)+k_app*y(e)*y(ORgate_E_K__k)+k_app*y(f)*y(ORgate_F_K__k);
dy(ORgate_G_L__l)=-k_app*y(g)*y(ORgate_G_L__l);
dy(ORgate_H_L__l)=-k_app*y(h)*y(ORgate_H_L__l);
dy(ORthd_L)=-k_app_thd*y(l)*y(ORthd_L);
dy(l)=-k_app_thd*y(l)*y(ORthd_L)-k_app*y(l)*y(ORgate_L_N__n)+k_app*y(g)*y(ORgate_G_L__l)+k_app*y(h)*y(ORgate_H_L__l);
dy(ORgate_I_M__m)=-k_app*y(i)*y(ORgate_I_M__m);
dy(ORgate_J_M__m)=-k_app*y(j)*y(ORgate_J_M__m);
dy(ORthd_M)=-k_app_thd*y(m)*y(ORthd_M);
dy(m)=-k_app_thd*y(m)*y(ORthd_M)-k_app*y(m)*y(ORgate_M_O__o)+k_app*y(i)*y(ORgate_I_M__m)+k_app*y(j)*y(ORgate_J_M__m);
dy(ORgate_K_N__n)=-k_app*y(k)*y(ORgate_K_N__n);
dy(ORgate_L_N__n)=-k_app*y(l)*y(ORgate_L_N__n);
dy(ORthd_N)=-k_app_thd*y(n)*y(ORthd_N);
dy(n)=-k_app_thd*y(n)*y(ORthd_N)-k_app*y(n)*y(ORgate_N_O__o)+k_app*y(k)*y(ORgate_K_N__n)+k_app*y(l)*y(ORgate_L_N__n);
dy(ORgate_M_O__o)=-k_app*y(m)*y(ORgate_M_O__o);
dy(ORgate_N_O__o)=-k_app*y(n)*y(ORgate_N_O__o);
dy(ORthd_O)=-k_app_thd*y(o)*y(ORthd_O);

end
